name: Publish python distribution to PyPI

on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/poetry-t-ymorishima030
    permissions:
      id-token: write
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          python -m pip install poetry-dynamic-versioning

      - name: Install poetry dependencies
        run: |
          poetry lock
          poetry install --no-ansi

      - name: Poetry build
        run: |
          poetry build

      - name: Publish package distributions to testPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
