name: Publish python distribution to PyPI and TestPyPI

on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry Action
        uses: snok/install-poetry@v1
        with:
          path: ~/.venv

      - name: Cashe venv
        uses: actions/cache@v2
        id: venv-cache
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Poetry config set
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config http-basic.testpypi __token__ ${{ secrets.TEST_PYPI_PASSWORD }}

      - name: Install dependencies
        if: steps.venv-cache.outputs.cache-hit != 'true'
        run: |
          poetry lock
          poetry install --no-ansi

      - name: Poetry build
        run: |
          poetry build

      - name: Poetry publish
        run: |
          poetry publish -r testpypi
