name: Publish python distribution to PyPI and TestPyPI

on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          pip install poetry-dynamic-versioning

      - name: Poetry config set
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config http-basic.testpypi __token__ ${{ secrets.TEST_PYPI_PASSWORD }}

      - name: Install dependencies
        run: |
          poetry lock
          poetry install --no-ansi

      - name: Poetry build
        run: |
          poetry build

      - name: Poetry publish
        run: |
          poetry publish -r testpypi
